### PR TITLE
be unambiguous

### PR DESCRIPTION
**Pull request by zeke**
avoid using letters that are difficult to visually distinguish: 0Ool1

### CODE REVIEW

**Comment by zeke** [comment]
bump bump

**Comment by eliaskg** [comment]
Thanks! Thinking about providing several options for the random string. This could be one of them.

**Comment by zeke** [comment]
:+1:

**Comment by houmark** [comment]
+1

**Comment by zeke** [comment]
Every once in a while I'll have to enter a code somewhere with a 0 or O in it. Every time that happens this PR creeps back into my memory.

**Comment by houmark** [comment]
Agreed, but the new list you proposed in your commit includes I and i — I think those chars should be removed as well.

Would be nice to be able to provide your own char list as an option.

**Comment by houmark** [comment]
Meanwhile rand-token has what you are looking for @zeke - it's an easy plug in replacement:
https://www.npmjs.com/package/rand-token

**Comment by eliaskg** [comment]
This function is now included in 1.1.0.

**Comment by zeke** [comment]
Nice!

**Pull request closed without merging**
